posts/urls.py
from django.urls import path, re_path

from . import views
from . import feed

app_name = "posts"

urlpatterns = [
    path('', views.index, name='index'),
    path('rss', feed.LatestPostsFeed(), name='rss'),
    re_path(r'^(?P<post_id>\d+)[-\w]*$', views.post, name='post'),
]

projects/urls.py
from django.urls import path, re_path

from . import views

app_name = "projects"

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<project_id>\d+)[-\w]*$', views.project, name='project'),
]

website/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # Examples:
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('favorites/', views.favorites, name='favorites'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('projects/', include('projects.urls', namespace='projects')),

    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse
import datetime
import re
import bleach


class Post(models.Model):
    title = models.CharField(max_length=100)
    pubdate = models.DateField(auto_now_add=True, editable=True)
    visible = models.BooleanField(default=True)
    content = models.TextField()

    #Show this post on the homepage
    on_front_page = models.BooleanField(default=False)
    #Show this post as a "top post"
    top_post = models.BooleanField(default=False)

    hacker_news_link = models.URLField(blank=True)

    class Meta:
        ordering = ['-pubdate']

    def publish(self):
        self.pubdate = datetime.date.today()
        self.visible = True
        self.save()

    def __str__(self):
        return self.title

    def preview(self):
        return self.content.partition("\n")[0]

    def clean_preview(self):
        return bleach.clean(self.preview(), strip=True)

    def get_absolute_url(self):
        return reverse("posts:post", kwargs={'post_id': str(self.id)}) + "-" + self.title_slug()

    def title_slug(self):
        #Remove things other than word characters and spaces
        base = re.sub(r"[^\w ]", '', self.title)
        return base.replace(" ", "-").lower()

projects/models.py
from django.db import models
from django.urls import reverse
import datetime
import re


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    tagline = models.CharField(max_length=255)
    image = models.URLField()
    pubdate = models.DateField(auto_now_add=True, editable=True)
    visible = models.BooleanField(default=True)
    content = models.TextField()
    preview_content = models.TextField()

    #Show this project on the homepage
    on_front_page = models.BooleanField(default=False)

    class Meta:
        ordering = ['-pubdate']

    def publish(self):
        self.pubdate = datetime.date.today()
        self.visible = True
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("projects:project", kwargs={'project_id': str(self.id)}) + "-" + self.title_slug()

    def title_slug(self):
        #Remove things other than word characters and spaces
        base = re.sub(r"[^\w ]", '', self.title)
        return base.replace(" ", "-").lower()

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post


def index(request):
    posts = Post.objects.filter(visible=True)
    if request.user.has_perm('posts.view_hidden'):
        posts = Post.objects.all()

    return render(request, 'posts/index.html', {
        'posts': posts,
        'top_posts': posts.filter(top_post=True),
    })


def post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if not post.visible and not request.user.has_perm('posts.view_hidden'):
        raise Http404("Post not found")

    return render(request, 'posts/post.html', {
        'post': post
    })

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Project

# Create your views here.


def index(request):
    projects = Project.objects.filter(visible=True)
    if request.user.has_perm('projects.view_hidden'):
        projects = Project.objects.all()

    return render(request, 'projects/index.html', {
        'projects': projects
    })


def project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if not project.visible and not request.user.has_perm('projects.view_hidden'):
        raise Http404("Project not found")

    return render(request, 'projects/project.html', {
        'project': project
    })

website/views.py
from django.shortcuts import render

from posts.models import Post
from projects.models import Project


def home(request):
    return render(request, 'home.html', {
        "top_posts": Post.objects.filter(visible=True, on_front_page=True),
        "top_projects": Project.objects.filter(visible=True, on_front_page=True)
    })


def about(request):
    return render(request, 'about.html')

def favorites(request):
    return render(request, 'favorites.html')

templates/about.html
{% extends "splitpane.html" %}
{% load static %}

{%block title%}Brett van Zuiden | About me{%endblock%}

{%block js%}
<script src="{% static 'js/about.js' %}"></script>
{%endblock js%}

{%block contentpane%}
    <div class="about-intro fadein">
        <p class="motto"> My goal is to help people become more thoughtful, happy, and complete versions of themselves.</p>
        <p>
        I love creating mission-driven teams where diverse, talented people can excel individually and work together to change industries. I enjoy encouraging my peers and direct reports to stretch into new challenges and realize how talented they are. And I thrive working in education, where I can dedicate my career to helping children realize their full potential.
        </p>
        <p>
        Outside of work, I cook, surf, hack on a number of side projects, and play soccer and guitar. I currently live in Oakland.
        </p>
    </div>
    <ul class="timeline-entries fadein">
        <li>
            <h3>Head of Product at Once</h3>
            <time>July 2025 to Present</time>
            <p class="description">Once helps every child learn to read. Students using Once receive 15 minutes of 1-on-1 literacy instruction every day from an in-person, caring adult, leading to life-changing results: last year, the typical student on Once accelerated from the 38th percentile to the 67th percentile on reading ability.</p>
            <p class="description">At Once, I lead all core product functions, including engineering, product management, design, and data.</p>
        </li>
        <li>
            <h3>CIO at Summit Public Schools</h3>
            <time>October 2022 to July 2025</time>
            <p class="description">Summit Public Schools is a leading network of public schools that prepares a diverse student population for success in a four-year college and to be thoughtful, contributing members of society.</p>
            <p class="description">As CIO, I led a team of analysts and data engineers to support our schools with systems and insights to better serve students:</p>
            <ul class="highlights">
                <li>Reimagined and redesigned core operational workflows using technology across attendance, enrollment, assessment, state reporting, teaching coaching, and more, eliminating tasks from school leaders while improving quality and compliance.</li>
                <li>Led organization-wide change management in the adoption of a new Learning Management System, including assembling an evaluation &amp; selection team, managing buildout and customization, and coordinating training and rollout across our 12 schools and 3500+ students and families.</li>
                <li>Managed team through significant restructuring, reducing cost by 50% but noticeably improving team velocity and impact through investments in automation.</li>
                <li>Founded Marshall Data Partners, a new innovation initiative within Summit to provide data engineering and operations to partner organizations, including fundraising seed grants and landing initial customers.</li>
                <li>Designed and implemented performance management framework for the team, as well as designed and led Home Office professional development.</li>
                <li>Partnered with our executive team and school leaders to help them leverage technology and data to improve their team's performance, including our annual goal setting and progress monitoring.</li>
            </ul>
        </li>
        <li>
            <h3>Product Lead at Outschool</h3>
            <time>October 2020 to October 2022</time>
            <p class="description">I had an amazing time working with a team of PMs, researchers, designers, and engineers to help kids and teens love learning.</p>
            <p class="description">
                I started at Outschool in 2020 as one of the first PMs, where I helped craft the product team culture along with leading our learner-focused products. Building products for kids was a blast - some particular highlights out of the things I worked on:
            </p>
            <ul class="highlights">
                <li>Founded the initial Learner Product Group, growing it from single pod of 5 to a team of 20, including hiring and managing two PMs</li>
                <li>Launched learner-led class discovery, generating over $4M in bookings/year</li>
                <li>Proposed and launched Outschool Groups, interest-based social networks for kids aged 8-15, and Outschool's first mobile app.</li>
                <li>Collaborated closely with Trust &amp; Safety and Legal teams to ensure learners were safe on Outschool, including introducing content moderation &amp; administering our 100k+ account Zoom infrastructure </li>
                <li>Led weekly PM team training and created PM leveling rubric</li>
            </ul>
        </li>
        <li>
            <h3>PM Lead at Clever</h3>
            <time>April 2015 to October 2020</time>
            <p class="description">I was very fortunate to spend over 5 years working alongside a talented and thoughtful team to build software that helps students learn and teachers teach.</p>
            <ul class="highlights">
                <li>Built the Discovery team, a new line of business for Clever, from a 2 person experimental initiative into a 18 person cross-functional team, initial revenue, and top-level company priority.</li>
                <li>As part of the Discovery team work, built the Clever Library, the #1 place for teachers to find and adopt edtech, used by over 10% of US teachers.</li>
                <li>Previously led Clever's school-facing product work, growing our active users from 100,000 to 4.5M over 18 months.</li>
                <li>Built, launched, and scaled Clever Badges, Clever's highest NPS product, now used by 20% of U.S. K-2 students.</li>
                <li>Mentored, hired, and managed entry level and mid-career product managers.</li>
                <li>Taught "Freshman Seminar," a six week training program for new hires to learn about the K12 education ecosystem.</li>
            </ul>
        </li>
        <li>
            <h3>Head of Product Management at IFTTT</h3>
            <time>May 2014 to April 2015</time>
            <p class="description">I worked with a team of 12 fantastic engineers and designers to build and grow IFTTT’s consumer products on iOS, Android, and the web. I headed up IFTTT's product roadmap, growth, metrics &amp; user research, and day-to-day process.</p>
            <p class="description">As the first product manager, I established the role of product management at IFTTT, and built out the initial team.</p>
            <ul class="highlights">
                <li>Built out a flagship product (Do) from initial conception to public launch.</li>
                <li>Increased success rate of the web onboarding flow by 43%.</li>
                <li>Coordinated a major brand update and simultaneous launch of 8 new apps across iOS and Android.</li>
                <li>Doubled the clickthrough rate and halved the unsubscribe rate of our email engagement efforts.</li>
            </ul>
        </li>
        <li>
            <h3>Founder and CEO at Filepicker.io</h3>
            <time>January 2012 to April 2014</time>
            <p class="description">
                As the CEO, I drove the product, business, and technical direction of the company; as a
                founder, I did everything from UX design, fundraising, and hiring to coding the iOS product, 
                content marketing, and customer support.
            </p>
            <ul class="highlights">
                <li>Grew the company to 13 people and an AMR of $600,000 with over 1,000 customers.</li>
                <li>Participated in the YCombinator batch of Summer 2012.</li>
                <li>Raised $1.8mn from Andreessen Horowitz and other investors.</li>
                <li>Reached profitability in 18 months.</li>
                <li>Sold to Xenon Ventures in spring of 2014.</li>
            </ul>
        </li>
        <li>
            <h3>S.B. in Computer Science and Electrical Engineering at MIT</h3>
            <time>August 2008 to June 2012</time>
            <p class="description">
                GPA: 5.0/5.0. Minors in Mechanical Engineering, Mathematics.
            </p>
            <ul class="highlights">
                <li>McGovern Award for significant impact on entrepreneurship - MIT, 2012</li>
                <li>Top 5 Graduating MIT computer scientists - ThePhenomList, 2012</li>
                <li>Whitelaw Prize for Originality of Design - MIT, 2010</li>
            </ul>
        </li>
    </ul>
</div>
{%endblock%}

{%block sidepane%}
{{block.super}}
<div class="timeline fadein">
    <svg id="timeline-graphic" width="200" height="3200" viewBox="0 0 200 3200"></svg>
</div>
{%endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="Copyright" content="Brett van Zuiden" />
        <meta name="keywords" content="Brett van Zuiden, about me, resume, product manager" />
        <meta name="description" content="{%block description%}{%endblock%}" />
        <meta name="og:site_name" content="Brettcvz.com" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {%block og_tags%}{%endblock%}

        <!-- Favicons -->
        <!-- TODO -->
        <link rel="apple-touch-icon" href="/s/img/icon-touch.e4872c4da341.png">
        <link rel="icon" sizes="192x192" href="/s/img/icon-touch.e4872c4da341.png">
        <link rel="shortcut icon" href="/s/img/favicon.6dbf28c0650e.ico">

        <title>{%block title%}Brett van Zuiden | Maker, Hobbyist, Optimist{%endblock%}</title>
        <link href='//fonts.googleapis.com/css?family=Dosis:400,600|Josefin+Sans:300,400,600|Neuton:200,200italic,300,400' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {%block css%}{%endblock%}
    </head>
    <body>
        <div class="wrapper">
            {%block body%}
            {%endblock%}
            <div class="push"></div>
        </div>
        <footer>&copy; Brett van Zuiden</footer>
		<!-- Google tag (gtag.js) -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-58839547-1"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'UA-58839547-1');
		</script>
		<script src="{% static 'js/base.js' %}"></script>
		{%block js%}{%endblock%}
    </body>
</html>

templates/favorites.html
{% extends "splitpane.html" %}

{%block title%}Brett van Zuiden | My favorite corners of the internet{%endblock%}

{%block contentpane%}
<article class="post">
  <h1>My favorite corners of the internet</h1>
  <p>In the age of search engines and social media, it feels a bit quaint to maintain a catalog of links, but hopefully it will help a reader or two discover something new.</p>

  <h3>Interesting perspectives on tech</h3>
  <ul>
    <li><a target="st" href="https://stratechery.com/">Stratechery</a></li>
    <li><a target="ad" href="https://alexdanco.com/">Alex Danco</a></li>
    <li><a target="be" href="https://www.ben-evans.com/">Benedict Evans</a></li>
    <li><a target="hn" href="https://news.ycombinator.com/">HackerNews</a></li>
    <li><a target="rod" href="https://www.eugenewei.com">Remains of the Day</a></li>
  </ul>
  <h3>Interesting perspectives on non-tech</h3>
  <ul>
    <li><a target="ssc" href="https://slatestarcodex.com/">StarSlateCodex</a></li>
    <li><a target="wbw" href="https://waitbutwhy.com/">WaitByWhy</a></li>
    <li><a target="sg" href="https://seths.blog/">Seth Godin</a></li>
    <li><a target="lw" href="https://www.lesswrong.com">LessWrong</a></li>
    <li><a target="rf" href="https://www.ribbonfarm.com/for-new-readers/">RibbonFarm</a></li>
    <li><a target="twd" href="https://andrewsullivan.substack.com/">The Weekly Dish</a></li>
    <li><a target="tss" href="https://scholars-stage.blogspot.com/">The Scholar's Stage</a></li>
    <li><a target="sa" href="https://www.scottaaronson.com/blog/">Scott Aaronson</a></li>
  </ul>
  <h3>Hobbies</h3>
  <ul>
    <li><a target="tsp" href="http://www.tastespotting.com">Tastespotting</a></li>
    <li><a target="se" href="https://www.seriouseats.com">SeriousEats</a></li>
    <li><a target="jg" href="https://www.justinguitar.com">JustinGuitar</a></li>
  </ul>
  <h3>Comics & Just for fun</h3>
  <ul>
    <li><a target="smbc" href="https://www.smbc-comics.com/">Saturday Morning Breakfast Cereal</a></li>
    <li><a target="xkcd" href="http://xkcd.com/">XKCD</a></li>
    <li><a target="ec" href="http://existentialcomics.com/">Existential Comics</a></li>
    <li><a target="hpmor" href="http://www.hpmor.com/">Harry Potter and the Methods of Rationality</a> (and the "sequel," <a target="sd" href="http://www.anarchyishyperbole.com/p/significant-digits.html">Significant Digits</a>)</li>
  </ul>
</article>
{%endblock%}

templates/home.html
{% extends "base.html" %}
{%block title%}Brett van Zuiden | Maker, Hobbyist, Optimist{%endblock%}

{%block description%}
The web presence of Brett van Zuiden - posts, projects, and work history.
{%endblock%}

{%block og_tags%}
<meta name="og:title" content="Brett van Zuiden" />
<meta name="og:desription" content="The web presence of Brett van Zuiden - posts, projects, and work history." />
{%endblock%}

{%block body%}
<div id="content">
    <div id="opener" class="fadein">
        <img class="headshot" src="https://www.gravatar.com/avatar/3ccacf24c4f98c47c5346f6d09135d9c.png&s=100" alt="A picture of me">
        <p id="intro">
        Hi, my name is <strong>Brett van Zuiden</strong>.
        <br/>I am a maker, a hobbyist, and an optimist.
        <br/>I live in Oakland.
        </p>
    </div>
    <div class="segment fadein" id="about">
        <h2><a href="{%url 'about'%}">About</a></h2>
        <div class="details">
            <ul id="main-points">
                <li>Head of Product at <a target="once" href="https://tryonce.com">Once</a></li>
                <li>Former CIO at <a target="summit" href="https://summitps.org">Summit Public Schools</a></li>
                <li>Former PM Lead at <a target="clever" href="https://clever.com">Clever</a>, <a target="outschool" href="https://outschool.com">Outschool</a></li>
                <li>Founding CEO of <a target="fp" href="https://filestack.com">Filestack</a></li>
                <li>Studied <abbr title="Electrical Engineering and Computer Science">EECS</abbr>, Math, and Mechanical Engineering at MIT</li>
            </ul>
            <a class="more" href="{% url 'about'%}">More about me &rsaquo;</a>
        </div>
    </div>
    <div class="segment fadein" id="posts">
        <h2><a href="{% url 'posts:index'%}">Posts</a></h2>
        <div class="details">
            <ul id="top-posts">
                {%for post in top_posts%}
                <li>
                    <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                    <p>
                    {{post.clean_preview|safe}} <a class="readmore" href="{{post.get_absolute_url}}">&rsaquo;</a>
                    </p>
                </li>
                {%endfor%}
            </ul>
            <a class="more" href="{% url 'posts:index'%}">See all posts &rsaquo;</a>
        </div>
    </div>
    <div class="segment fadein" id="projects">
        <h2><a href="{% url 'projects:index'%}">Projects</a></h2>
        <div class="details">
            <ul id="top-projects">
                {%for project in top_projects%}
                <li class="expanded">
                    <a href="{{project.get_absolute_url}}">
                        <img src="{{project.image}}">
                    </a>
                    <h4><a href="{{project.get_absolute_url}}">{{project.title}}</a></h4>
                    <p>{{project.tagline}}</p>
                </li>
                {%endfor%}
            </ul>
            <a class="more" href="{% url 'projects:index'%}">See all projects &rsaquo;</a>
        </div>
    </div>
    <div class="segment fadein" id="contact">
        <h2>Contact</h2>
        <div class="details">
            <a href="mailto:brettcvz@gmail.com">Brettcvz@gmail.com</a> &bull;
            <a href="http://www.linkedin.com/in/brettcvz">LinkedIn</a> &bull;
            <a href="http://github.com/brettcvz">Github</a>
        </div>
    </div>
</div>
{%endblock%}

templates/nav.html
<nav>
{%block nav%}
<ul>
    <li><a href="{%url 'home'%}">
            <img class="icon" src="http://www.gravatar.com/avatar/3ccacf24c4f98c47c5346f6d09135d9c.png&s=40" alt="A picture of me">
            <span class="entry">Brettcvz</span>
    </a></li>
    <li><a href="{%url 'about'%}">
            <span class="entry">About</span>
    </a></li>
    <li><a href="{%url 'posts:index'%}">
            <span class="entry">Posts</span>
    </a></li>
</ul>
{%endblock%}
</nav>

templates/posts/base.html
{% extends "base.html" %}
{%block body%}
{%include "nav.html"%}

<div id="content">
    <div class="leftpane fadein">
        {%block leftpane%}
        {%endblock%}
    </div>
    <div class="sidepane fadein">
        <h3>Brett van Zuiden</h3>
        <h4>Maker, hobbyist, optimist</h4>
        <ul class="info">
            <li>I work as a Product Manager at <a href="http://ifttt.com">IFTTT</a>.</li>
            <li>I founded <a href="http://filepicker.io">Filepicker.io</a>, part of YC S12.</li>
            <li>Contact me at <a href="mailto:brettcvz@gmail.com">brettcvz@gmail.com</a></li>
        </ul>
    </div>
</div>
{%endblock%}

templates/posts/index.html
{% extends "splitpane.html" %}

{%block title%}Brett van Zuiden | Posts{%endblock%}

{%block contentpane%}
<div class="index-intro">
    <p>
        I write on things that interest me: product management, startups, and leading a fulfilled life.
    </p>
    <p>
      New posts weekly - subscribe via
        <a href="mailto:brettcvz@gmail.com?subject=Please send me new posts via email" target="email">email</a>
        or
        <a href="/posts/rss" target="rss">
          RSS
          <svg xmlns="http://www.w3.org/2000/svg"
               id="RSSicon"
               viewBox="0 0 8 8" width="16" height="16">

            <title>RSS feed icon</title>

            <style type="text/css">
              .button {stroke: none; fill: orange;}
              .symbol {stroke: none; fill: white;}
            </style>

            <rect   class="button" width="8" height="8" rx="1.5" />
            <circle class="symbol" cx="2" cy="6" r="1" />
            <path   class="symbol" d="m 1,4 a 3,3 0 0 1 3,3 h 1 a 4,4 0 0 0 -4,-4 z" />
            <path   class="symbol" d="m 1,2 a 5,5 0 0 1 5,5 h 1 a 6,6 0 0 0 -6,-6 z" />

          </svg>
        </a>
    </p>
    <p>
      For even better content, see <a href="/favorites">some of my favorite corners of the internet</a>.
    </p>
    <!--
        If you're looking to get a sense of what I write about, read these posts:
    <ol>
        {%for post in top_posts%}
        <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
        {%endfor%}
    </ol>
    -->
</div>
<div class="posts">
    {% for post in posts%}
    <article>
        <h2 {%if not post.visible%}class="unpublished"{%endif%}>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </h2>
        <time class="pubdate" datetime="{{post.pubdate|date:"Y-m-d"}}">{{post.pubdate|date:"F jS, Y"}}</time>
        <p class="preview">
        {{post.clean_preview|safe}} <a class="readmore" href="{{post.get_absolute_url}}">Read more &rsaquo;</a>
        </p>
    </article>
    {% endfor %}
</div>
{%endblock%}

templates/posts/post.html
{% extends "splitpane.html" %}

{%block title%}Brett van Zuiden | {{post.title}}{%endblock%}

{%block description%} {{post.clean_preview}} {%endblock%}

{%block og_tags%}
<meta name="og:title" content="{{post.title}}" />
<meta name="og:desription" content="{{post.preview}}" />
{%endblock%}

{%block contentpane%}
<article class="post">
    <h1 {%if not post.visible%}class="unpublished"{%endif%}>{{post.title}}</h1>
    <time class="pubdate" datetime="{{post.pubdate|date:"Y-m-d"}}">{{post.pubdate|date:"F jS, Y"}}</time>
    {{post.content|safe|linebreaks}}
    {%if perms.posts.can_edit%}
    <p><a href="/admin/posts/post/{{post.id}}" target="edit_{{post.id}}">Edit Post</a></p>
    {%endif%}
</article>
<div class="article-footer">
  <p class="feedback">
    {%if post.hacker_news_link%}
    Feedback or suggestions? Comment on <a href="{{post.hacker_news_link}}">HackerNews</a>.
    {%else%}
    Feedback or suggestions? Send me an
      <a href="mailto:brettcvz@gmail.com?subject=Feedback on '{{post.title}}'" target="email">email</a>.
    {%endif%}
  </p>
  <p class="subscribe">
    New posts weekly - subscribe via
      <a href="mailto:brettcvz@gmail.com?subject=Please send me new posts via email" target="email">email</a>
      or
      <a href="/posts/rss" target="rss">
        RSS
        <svg xmlns="http://www.w3.org/2000/svg"
             id="RSSicon"
             viewBox="0 0 8 8" width="16" height="16">

          <title>RSS feed icon</title>

          <style type="text/css">
            .button {stroke: none; fill: orange;}
            .symbol {stroke: none; fill: white;}
          </style>

          <rect   class="button" width="8" height="8" rx="1.5" />
          <circle class="symbol" cx="2" cy="6" r="1" />
          <path   class="symbol" d="m 1,4 a 3,3 0 0 1 3,3 h 1 a 4,4 0 0 0 -4,-4 z" />
          <path   class="symbol" d="m 1,2 a 5,5 0 0 1 5,5 h 1 a 6,6 0 0 0 -6,-6 z" />

        </svg>
      </a>
  </p>
</div>
{%endblock%}

templates/projects/base.html
{% extends "base.html" %}

templates/projects/index.html
{% extends "splitpane.html" %}

{%block title%}Brett van Zuiden | Projects{%endblock%}

{%block contentpane%}
<div class="index-intro">
    <p>
        I like building all sorts of things, mostly to play around with concepts I think are interesting or solve some small need.
    </p>
</div>
<div class="projects">
    {% for project in projects%}
    <article>
        <h2 {%if not project.visible%}class="unpublished"{%endif%}>
            <a href="{{project.get_absolute_url}}">{{project.title}}</a>
        </h2>
        <time class="pubdate" datetime="{{project.pubdate|date:"Y-m-d"}}">{{project.pubdate|date:"F jS, Y"}}</time>
        <p class="preview">
            {{project.preview_content|safe}}
            <a class="readmore" href="{{project.get_absolute_url}}">Read more &rsaquo;</a>
        </p>
    </article>
    {% endfor %}
</div>
{%endblock%}

templates/projects/project.html
{% extends "splitpane.html" %}

{%block title%}Brett van Zuiden | {{project.title}}{%endblock%}

{%block description%} {{project.tagline}} {%endblock%}

{%block og_tags%}
<meta name="og:title" content="{{project.title}}" />
<meta name="og:desription" content="{{project.tagline}}" />
<meta name="og:url" content="https://brettcvz.com{{project.get_absolute_url}}" />
<meta name="og:image" content="{{project.image}}" />
{%endblock%}

{%block contentpane%}
<article class="project">
    <h1 {%if not project.visible%}class="unpublished"{%endif%}>{{project.title}}</h1>
    <time class="pubdate" datetime="{{project.pubdate|date:"Y-m-d"}}">{{project.pubdate|date:"F jS, Y"}}</time>
    {{project.content|safe}}
    {%if perms.project.can_edit%}
    <p><a href="/admin/projects/project/{{project.id}}" target="edit_{{project.id}}">Edit Project</a></p>
    {%endif%}
</article>
{%endblock%}

templates/splitpane.html
{% extends "base.html" %}
{%block body%}

<div id="content">
    <div class="sidepane fadein">
        <h3><a href="{%url 'home'%}">Brett van Zuiden</a></h3>
        <nav>
            <a href="{%url 'posts:index'%}">Posts</a> |
            <a href="{%url 'projects:index'%}">Projects</a> |
            <a href="{%url 'about'%}">About</a>
        </nav>
        {%block sidepane%}
        <ul class="info">
			<li>I work as Head of Product at <a href="https://tryonce.com">Once</a>.</li>
            <li>I used to work at <a href="https://clever.com">Clever</a>, <a href="https://outschool.com">Outschool</a>, &amp; <a href="https://summitps.org">Summit</a></li>
            <li>Contact me at <a href="mailto:brettcvz@gmail.com">brettcvz@gmail.com</a></li>
        </ul>
        {%endblock%}
    </div>
    <div class="rightpane fadein">
        {%block contentpane%}
        {%endblock%}
    </div>
</div>
{%endblock%}